"""
Unit tests for the /nlq answer cache.
"""

from app.config import settings
from app.services.query_cache import QueryCache


class TestQueryCache:
    def setup_method(self):
        self._saved = {
            "query_cache_enabled": settings.query_cache_enabled,
            "use_redis": settings.use_redis,
        }
        settings.query_cache_enabled = True
        settings.use_redis = False  # exercise the in-memory path deterministically
        self.cache = QueryCache()

    def teardown_method(self):
        for key, value in self._saved.items():
            setattr(settings, key, value)

    def test_miss_on_first_lookup(self):
        assert self.cache.get("ds1", "average age?", "openai", "gpt-4o-mini") is None

    def test_hit_after_set(self):
        response = {"answer": "42", "code": "result = 42", "execution_success": True}
        self.cache.set("ds1", "average age?", "openai", "gpt-4o-mini", response)
        assert self.cache.get("ds1", "average age?", "openai", "gpt-4o-mini") == response

    def test_question_casing_and_whitespace_do_not_change_the_key(self):
        response = {"answer": "42", "execution_success": True}
        self.cache.set("ds1", "Average Age?", "openai", "gpt-4o-mini", response)
        assert self.cache.get("ds1", "  average age?  ", "openai", "gpt-4o-mini") == response

    def test_different_dataset_misses(self):
        self.cache.set("ds1", "q", "openai", "gpt-4o-mini", {"answer": "a"})
        assert self.cache.get("ds2", "q", "openai", "gpt-4o-mini") is None

    def test_different_question_misses(self):
        self.cache.set("ds1", "q1", "openai", "gpt-4o-mini", {"answer": "a"})
        assert self.cache.get("ds1", "q2", "openai", "gpt-4o-mini") is None

    def test_different_provider_misses(self):
        """A provider switch shouldn't serve a cached answer generated by a
        different model — quality/behavior can differ meaningfully."""
        self.cache.set("ds1", "q", "openai", "gpt-4o-mini", {"answer": "a"})
        assert self.cache.get("ds1", "q", "anthropic", "gpt-4o-mini") is None

    def test_different_model_misses(self):
        self.cache.set("ds1", "q", "openai", "gpt-4o-mini", {"answer": "a"})
        assert self.cache.get("ds1", "q", "openai", "gpt-4o") is None

    def test_different_context_misses(self):
        """A follow-up question's meaning depends on the conversation so
        far — caching without the context in the key could serve the wrong
        answer to a context-dependent question."""
        self.cache.set("ds1", "what about last year?", "openai", "gpt-4o-mini", {"answer": "a"})
        context = [{"question": "revenue by region?", "answer": "..."}]
        assert (
            self.cache.get("ds1", "what about last year?", "openai", "gpt-4o-mini", context) is None
        )

    def test_same_context_hits(self):
        context = [{"question": "revenue by region?", "answer": "..."}]
        self.cache.set(
            "ds1", "what about last year?", "openai", "gpt-4o-mini", {"answer": "a"}, context
        )
        assert self.cache.get("ds1", "what about last year?", "openai", "gpt-4o-mini", context) == {
            "answer": "a"
        }

    def test_disabled_never_hits(self):
        settings.query_cache_enabled = False
        self.cache.set("ds1", "q", "openai", "gpt-4o-mini", {"answer": "a"})
        assert self.cache.get("ds1", "q", "openai", "gpt-4o-mini") is None

    def test_memory_store_is_bounded(self):
        from app.services import query_cache as qc_module

        original_max = qc_module.MAX_MEMORY_ENTRIES
        qc_module.MAX_MEMORY_ENTRIES = 3
        try:
            for i in range(5):
                self.cache.set(f"ds{i}", "q", "openai", "gpt-4o-mini", {"answer": str(i)})
            assert len(self.cache._memory_store) == 3
            # Oldest entries evicted first.
            assert self.cache.get("ds0", "q", "openai", "gpt-4o-mini") is None
            assert self.cache.get("ds4", "q", "openai", "gpt-4o-mini") == {"answer": "4"}
        finally:
            qc_module.MAX_MEMORY_ENTRIES = original_max
